--------------------------------------------------------
--  File created - Sunday-May-02-2021   
--------------------------------------------------------
@C:\Users\jenit\ANALYZE_150_PROC.sql
@C:\Users\jenit\BANK_INPUT.sql
@C:\Users\jenit\BOLLINGER_PROC.sql
@C:\Users\jenit\EVENTS_PROC.sql
@C:\Users\jenit\FUNDA_POINTS_PROC.sql
@C:\Users\jenit\NASDAQ_AVG_PROC_DAILY.sql
@C:\Users\jenit\NASDAQ_POSTIVE_PROC.sql
@C:\Users\jenit\NASDAQ_VOL_PROC.sql
@C:\Users\jenit\RSI_PROC.sql
@C:\Users\jenit\SPLIT_PROC.sql
@C:\Users\jenit\STOCK_SPLIT_STATUS.sql
@C:\Users\jenit\BOLLINGER.sql
@C:\Users\jenit\FUNDA_POINT_FN.sql
@C:\Users\jenit\MIN_MAX_PRICE_FN.sql
@C:\Users\jenit\NASAVG.sql
@C:\Users\jenit\NASDAQ_TAB.sql
@C:\Users\jenit\NASDAQ_VOL_TAB.sql
@C:\Users\jenit\NAS_PRIVCLOSE.sql
@C:\Users\jenit\PRICEPOINTS.sql
@C:\Users\jenit\PRICE_POINT_FN.sql
@C:\Users\jenit\QOQ_EPS.sql
@C:\Users\jenit\QOQ_REV.sql
@C:\Users\jenit\QUAT_EPS.sql
@C:\Users\jenit\QUAT_REVENUE.sql
@C:\Users\jenit\TCH_CNT.sql
@C:\Users\jenit\TCH_VOL_CNT.sql
@C:\Users\jenit\VOLPOINTS.sql
@C:\Users\jenit\VTOP.sql
@C:\Users\jenit\YEAR_EPS.sql
@C:\Users\jenit\YEAR_REVENUE.sql
